### ISSUE TITLE
After install UI not working - windows

### ISSUE THREAD

**Issue by bdshanto** [sefatanam/pretty-home#1]
![image](https://github.com/user-attachments/assets/a77f30f8-6fec-4b9e-b8d3-dd13f600f46c)

**Comment by sefatanam** [comment]
Hi @bdshanto , This issue tagged as feature-request, currently, the Pretty Home UI can be accessed via the command palette by typing `pretty home`. In the upcoming release, I plan to introduce a configuration option that will allow users to replace the default VS Code welcome page with Pretty Home.

I appreciate your feedback, Thank you

**Comment by sefatanam** [comment]
Hi @bdshanto 

🚀 New in version `1.1.0` of Pretty Home: Introducing `Pretty Home: Settings` in the command palette. Customize whether it loads by default on your homepage. Update now!

**Comment by singularitti** [comment]
Hi @sefatanam, I tried the `v1.1.1` version, but when I start up VSCode, this page is still not shown. Even after I have the following settings:
```json
{
"prettyHome.showOnStartup": true,
"workbench.startupEditor": "none" // This option does not change anything
}
```

**Comment by sefatanam** [comment]
@singularitti , yeah, I noticed there is a problem to load it on the startup, but sometimes moved to another app and back to vscode then it worked well. I'm looking forward to this issue.

Please confirm that you able to load the extension from the command palette?

**Comment by singularitti** [comment]
Hi @sefatanam, thanks for the timely reply!

> Please confirm that you able to load the extension from the command palette?

Yes. I can turn it on with "Pretty Home: Recent Projects" command.

Also, I don't like the notification "Pretty Home Initialized ✨" every time. Can we turn it off? Thanks!

**Comment by sefatanam** [comment]
@singularitti, Thanks for your feedback, I'm also planing to remve the notification in next release.

**Comment by singularitti** [comment]
Good, now it works! But 1 potential bug: if I have this extension installed in multiple profiles, when switching between them, the same summary page will be opened multiple times. But I expect it should be opened only once. Could you reproduce? Is it possible to fix it?

**Comment by sefatanam** [comment]
Hi @singularitti 

I didn't test it on multiple profiles. Can you please provide me the steps how you can reproduce the issue?

**Comment by singularitti** [comment]
Hi @sefatanam, I have put it in #3.
