### ISSUE TITLE
Bug Report: Issue with Recent Projects Display on Profile Switch

### ISSUE THREAD

**Issue by singularitti** [sefatanam/pretty-home#3]
**Steps to Reproduce:**
1. **Create a Profile:** Follow the instructions to [create a profile](https://code.visualstudio.com/docs/editor/profiles#_create-a-profile) in Visual Studio Code.
2. **Install Extension:** Install the desired extension within this profile.
3. **Switch Profiles:** [Switch to another profile](https://code.visualstudio.com/docs/editor/profiles#_switch-profiles) in Visual Studio Code.
4. **Install Extension Again:** Install the same extension in the new profile.
5. **Restart VSCode:** Quit Visual Studio Code and restart the application.

**Observed Behavior:**
- Upon restarting, the "Recent Projects" page of the initial profile is displayed.
- Switching to another profile displays the "Recent Projects" in a separate tab.

**Expected Behavior:**
- The "Recent Projects" should reflect the current profile's recent projects list, without being carried over or displayed in a separate tab.

**Comment by sefatanam** [comment]
Hi @singularitti 

I'm pleased that this extension has been helpful to you. I look forward to this issue. Thanks

**Comment by sefatanam** [comment]
Note: In VS Code extensions, the state is not persistent once you switch profiles. This causes issues with tracking previously opened recent project tabs, as they cannot be properly disposed of. When a profile switch occurs, the extension's activate function runs again, but the deactivate function does not wait for promises to resolve, leading to webview cleanup issues. Additionally, globalState is scoped to the workspace, which prevents it from remembering the state of previously opened tabs, as the reference gets destroyed.

Some Reference
- https://github.com/microsoft/vscode/issues/114688#issuecomment-768253918

VSCode Github Discussion
- https://github.com/microsoft/vscode-discussions/discussions/1346#discussioncomment-10179149

**Comment by sefatanam** [comment]
Hi @singularitti, 

### Version v1.1.3 is out now!

Please update the extension and give it a test. If it works for you, don’t forget to leave a star ⭐! Thanks! 😄

**Comment by singularitti** [comment]
Thanks, it is working now!

**Comment by singularitti** [comment]
Thanks! I have tried it and switch between profiles, after ~40 seconds on my computer it will still open a new tab displaying my recent projects when the first tab is not closed. Is it intended behavior?

<img width="1148" alt="image" src="https://github.com/user-attachments/assets/d93e394c-1faf-4e05-92e6-f020f6989590">

**Comment by sefatanam** [comment]
> Thanks! I have tried it and switch between profiles, after ~40 seconds on my computer it will still open a new tab displaying my recent projects when the first tab is not closed. Is it intended behavior?
> 
> <img width="1148" alt="image" src="https://github.com/user-attachments/assets/d93e394c-1faf-4e05-92e6-f020f6989590">
> 

This behavior is already under development. I manage to handle the state myself for VScode, a fix will roll out very soon.

**Comment by sefatanam** [comment]
hi @singularitti,

### Version v1.1.4 is out now!
Please update the extension and give it a test. Thanks

**Comment by singularitti** [comment]
It seems to be fixed! Thank you!
