### ISSUE TITLE
Bug Report: "Recent Projects" Displayed Upon Unhiding/Restoring VSCode Window on macOS

### ISSUE THREAD

**Issue by singularitti** [sefatanam/pretty-home#6]
**Steps to Reproduce:**

1. **Open VSCode:** Launch Visual Studio Code on macOS.
2. **Open a Project:** Open any project to ensure the main window is in use.
3. **Hide or Minimize VSCode:** Use Command+H to hide the application or minimize the open window to the Dock.
4. **Unhide or Restore:** Unhide the application or restore the minimized window from the Dock.
5. **Switch Apps:** Switch between different apps in the foreground and then return to VSCode.

**Observed Behavior:**

When the application is unhidden, the minimized window is restored, or when switching between different apps in the foreground, the "Recent Projects" page is displayed in the main window, even though no new window has been opened during this process.

**Expected Behavior:**

The main window should restore to its previous state, showing the currently open project without displaying the "Recent Projects" page.

**Questions:**

1. What might be causing this behavior where the "Recent Projects" page is displayed upon unhide/restore or app switching?
2. Is it possible to fix this issue so that the main window maintains its previous state without displaying the "Recent Projects" page?

**Comment by sefatanam** [comment]
@singularitti, can you provide me with a gif ? 

Basically if your workspace has any folder open that time it shouldn't open recent projects page. Let me revisit the event again. Thanks for your observations.

**Comment by sefatanam** [comment]
if someone encounter the same issue, will re-open this one.
